import 'material-design-icons-iconfont/dist/material-design-icons.css'
import "core-js/stable";
import "regenerator-runtime/runtime";
import Vue from "vue"
import Vuetify from "vuetify/lib"
import router from "./js/router"
import store from "./js/store"
import App from "./js/App"
import http from "./js/http"
import i18n from './i18n'
import vuetify from './plugins/vuetify';
import VueMatomo from 'vue-matomo';

import './sass/app.scss';

const API_BASE_URL = process.env.VUE_APP_API_BASE_URL;

window.onerror = function(message, source, line, column, error){
    try {
        var data = {
            name: error.name,
            message: error.message,
            source: source,
            line: line,
            column: column,
            location: window.location.href
        };

        if( "stack" in error )
        {
            data.stack = error.stack;
        }

        http.post(`${API_BASE_URL}/error_log`, data);
    }
    catch(e){ 
        //TODO: Error-Handling für den Error-Handler
    }
}

Vue.config.errorHandler = function (error, vm, info) {
    console.error(error);

    try {
        var data = {
            name: error.name,
            message: error.message,
            source: info,
            location: window.location.href
        };

        if( "stack" in error ){ data.stack = error.stack; }
        if( "fileName" in error ){ data.source = error.fileName; }
        if( "lineNumber" in error ){ data.line = error.lineNumber; }
        
        http.post(`${API_BASE_URL}/error_log`, data);
    }
    catch(e){ 
        //TODO: Error-Handling für den Error-Handler
    }
}

Vue.use(Vuetify);

Vue.use(VueMatomo, {
    // Configure your matomo server and site by providing
    host: process.env.VUE_APP_MATOMO_HOST,
    siteId: process.env.VUE_APP_MATOMO_SITE_ID,

    // Changes the default .js and .php endpoint's filename
    // Default: 'matomo'
    //trackerFileName: 'matomo',

    // Overrides the autogenerated tracker endpoint entirely
    // Default: undefined
    trackerUrl: 'https://stats.cramfire.com/cramfirep',

    // Overrides the autogenerated tracker script path entirely
    // Default: undefined
    trackerScriptUrl: 'https://stats.cramfire.com/cramfirej',

    // Enables automatically registering pageviews on the router
    router: router,

    // Enables link tracking on regular links. Note that this won't
    // work for routing links (ie. internal Vue router links)
    // Default: true
    enableLinkTracking: true,

    // Require consent before sending tracking information to matomo
    // Default: false
    requireConsent: false,

    // Whether to track the initial page view
    // Default: true
    trackInitialView: true,

    // Run Matomo without cookies
    // Default: false
    disableCookies: true,

    // Enable the heartbeat timer (https://developer.matomo.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page)
    // Default: false
    enableHeartBeatTimer: false,

    // Set the heartbeat timer interval
    // Default: 15
    heartBeatTimerInterval: 15,

    // Whether or not to log debug information
    // Default: false
    debug: false,

    // UserID passed to Matomo (see https://developer.matomo.org/guides/tracking-javascript-guide#user-id)
    // Default: undefined
    userId: undefined,

    // Share the tracking cookie across subdomains (see https://developer.matomo.org/guides/tracking-javascript-guide#measuring-domains-andor-sub-domains)
    // Default: undefined, example '*.example.com'
    cookieDomain: undefined,

    // Tell Matomo the website domain so that clicks on these domains are not tracked as 'Outlinks'
    // Default: undefined, example: '*.example.com'
    domains: ['*.cramfire.de', '*.cramfire.com'],

    // A list of pre-initialization actions that run before matomo is loaded
    // Default: []
    // Example: [
    //   ['API_method_name', parameter_list],
    //   ['setCustomVariable','1','VisitorType','Member'],
    //   ['appendToTrackingUrl', 'new_visit=1'],
    //   etc.
    // ]
    preInitActions: []
});

new Vue({
    store,
    router,
    i18n,
    vuetify,
    render: h => h(App)
}).$mount('#app');